[package]
name = "cerbos-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.10.0"
prost-types = "0.10.0"
testcontainers = "0.13.0"
tokio = { version = "1.17.0", features = ["full"] }
tonic = { version = "0.7.1", features = ["transport", "tls", "tls-roots"]}
tower = "0.4.12"
uuid = { version = "0.8.2", features = ["v4"] }

[build-dependencies]
tonic-build = "0.7.0"
