[package]
name = "cerbos"
version = "0.1.0"
edition = "2021"
description = "Rust SDK for working with Cerbos: an open core, language-agnostic, scalable authorization solution"
license = "Apache-2.0"
authors = ["Cerbos Developers <sdk+rust@cerbos.dev>"]
categories = ["api-bindings"]

[dependencies]
anyhow = "1.0.56"
prost = "0.10.0"
prost-types = "0.10.0"
testcontainers = "0.13.0"
tokio = { version = "1.17.0", features = ["full"] }
tonic = { version = "0.7.1", features = ["transport", "tls", "tls-roots"]}
tower = "0.4.12"
uuid = { version = "0.8.2", features = ["v4"] }

[build-dependencies]
tonic-build = "0.7.0"
