[package]
name = "cerbos"
version = "0.4.1"
edition = "2021"
description = "Rust SDK for working with Cerbos: an open core, language-agnostic, scalable authorization solution"
license = "Apache-2.0"
authors = ["Cerbos Developers <sdk+rust@cerbos.dev>"]
categories = ["api-bindings"]
repository = "https://github.com/cerbos/cerbos-sdk-rust"
homepage = "https://cerbos.dev"

[features]
testcontainers = []

[dependencies]
anyhow = "1.0.71"
prost = "0.11.9"
prost-types = "0.11.9"
testcontainers = "0.14.0"
tokio = { version = "1.29.1", features = ["full"] }
tonic = { version = "0.9.2", features = ["transport", "tls", "tls-roots"]}
tower = "0.4.13"
uuid = { version = "1.4.0", features = ["v4"] }

[build-dependencies]
tonic-build = "0.9.2"
