[package]
name = "cerbos"
version = "0.4.5"
edition = "2021"
description = "Rust SDK for working with Cerbos: an open core, language-agnostic, scalable authorization solution"
license = "Apache-2.0"
authors = ["Cerbos Developers <sdk+rust@cerbos.dev>"]
categories = ["api-bindings"]
repository = "https://github.com/cerbos/cerbos-sdk-rust"
homepage = "https://cerbos.dev"

[features]
testcontainers = []

[dependencies]
anyhow = "1.0.82"
hyper-util = { version = "0.1.7", features = ["tokio"] }
prost = "0.13.0"
prost-types = "0.13.0"
testcontainers = "0.21.0"
tokio = { version = "1.37.0", features = ["full"] }
tonic = { version = "0.12.0", features = ["transport", "tls", "tls-roots"]}
tower = "0.5.0"
uuid = { version = "1.8.0", features = ["v4"] }

[build-dependencies]
tonic-build = "0.12.0"
