// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClientCredentials {
    #[prost(string, tag = "1")]
    pub client_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub client_secret: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceToken {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub refresh_token: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub expires_at: ::core::option::Option<
        super::super::super::super::google::protobuf::Timestamp,
    >,
    #[prost(string, tag = "4")]
    pub token_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SavedCredentials {
    #[prost(string, tag = "1")]
    pub api_endpoint: ::prost::alloc::string::String,
    #[prost(oneof = "saved_credentials::Credentials", tags = "2, 3")]
    pub credentials: ::core::option::Option<saved_credentials::Credentials>,
}
/// Nested message and enum types in `SavedCredentials`.
pub mod saved_credentials {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Credentials {
        #[prost(message, tag = "2")]
        ClientCredentials(super::ClientCredentials),
        #[prost(message, tag = "3")]
        DeviceToken(super::DeviceToken),
    }
}
